version: '3.8'

services:
  proxy:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/tmp/agent_workspace
    environment:
      - OLLAMA_HOST=ollama:11434
      - REDIS_HOST=redis
    depends_on:
      - ollama
      - redis

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  ollama_data: