global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ollama-agent-proxy'
    static_configs:
      - targets: ['ollama-proxy:8000']
  
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']